/**
 * This class file was automatically generated by jASN1 (http://www.openmuc.org)
 */

package sjam;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.LinkedList;
import org.openmuc.jasn1.ber.*;
import org.openmuc.jasn1.ber.types.*;
import org.openmuc.jasn1.ber.types.string.*;

public final class SortingOrder {

	public byte[] code = null;
	public BerInteger unknown = null;

	public BerInteger unsorted = null;

	public BerInteger queryname = null;

	public BerInteger coordinate = null;

	public SortingOrder() {
	}

	public SortingOrder(byte[] code) {
		this.code = code;
	}

	public SortingOrder(BerInteger unknown, BerInteger unsorted, BerInteger queryname, BerInteger coordinate) {
		this.unknown = unknown;
		this.unsorted = unsorted;
		this.queryname = queryname;
		this.coordinate = coordinate;
	}

	public int encode(BerByteArrayOutputStream berOStream, boolean explicit) throws IOException {
		if (code != null) {
			for (int i = code.length - 1; i >= 0; i--) {
				berOStream.write(code[i]);
			}
			return code.length;

		}
		int codeLength = 0;
		if (coordinate != null) {
			codeLength += coordinate.encode(berOStream, true);
			return codeLength;

		}
		
		if (queryname != null) {
			codeLength += queryname.encode(berOStream, true);
			return codeLength;

		}
		
		if (unsorted != null) {
			codeLength += unsorted.encode(berOStream, true);
			return codeLength;

		}
		
		if (unknown != null) {
			codeLength += unknown.encode(berOStream, true);
			return codeLength;

		}
		
		throw new IOException("Error encoding BerChoice: No item in choice was selected.");
	}

	public int decode(InputStream iStream, BerIdentifier berIdentifier) throws IOException {
		int codeLength = 0;
		int choiceDecodeLength = 0;
		BerIdentifier passedIdentifier = berIdentifier;
		if (berIdentifier == null) {
			berIdentifier = new BerIdentifier();
			codeLength += berIdentifier.decode(iStream);
		}
		if (berIdentifier.equals(BerInteger.identifier)) {
			unknown = new BerInteger();
			codeLength += unknown.decode(iStream, false);
			return codeLength;
		}

		if (berIdentifier.equals(BerInteger.identifier)) {
			unsorted = new BerInteger();
			codeLength += unsorted.decode(iStream, false);
			return codeLength;
		}

		if (berIdentifier.equals(BerInteger.identifier)) {
			queryname = new BerInteger();
			codeLength += queryname.decode(iStream, false);
			return codeLength;
		}

		if (berIdentifier.equals(BerInteger.identifier)) {
			coordinate = new BerInteger();
			codeLength += coordinate.decode(iStream, false);
			return codeLength;
		}

		if (passedIdentifier != null) {
			return 0;
		}
		throw new IOException("Error decoding BerChoice: Identifier matched to no item.");
	}

	public void encodeAndSave(int encodingSizeGuess) throws IOException {
		BerByteArrayOutputStream berOStream = new BerByteArrayOutputStream(encodingSizeGuess);
		encode(berOStream, false);
		code = berOStream.getArray();
	}
}

